---
galaxy_info:
  author: ZSoftly Technologies
  description: SSH security hardening with UFW firewall and fail2ban
  company: ZSoftly Technologies Inc.
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

  galaxy_tags:
    - security
    - ssh
    - firewall
    - hardening

dependencies: []
