---
galaxy_info:
  author: ZSoftly
  description: Wazuh security monitoring agent
  company: ZSoftly
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

  galaxy_tags:
    - security
    - monitoring
    - siem

dependencies: []
