---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: not ansible_check_mode

- name: Restart otel-collector
  ansible.builtin.systemd:
    name: otel-collector
    state: restarted
  when: not ansible_check_mode
